### ISSUE TITLE
Whitespace in opening Partial Block expression?

### ISSUE THREAD

**Issue by leekelleher** [Handlebars-Net/Handlebars.Net#217]
Reading from the Handlebars specs, the opening Partial Block expressions appear to allow whitespace.

<http://handlebarsjs.com/partials.html#partial-block>

```handlebars
{{#> myPartial }}
  Failover content
{{/myPartial}}
```

This currently throws an exception, (I'm using the latest bleeding-edge build, v1.9.0-ci, from commit: a56efe840e213ea802cda91a2a36584312453703 - I haven't tested any other version/release).

<details>
<summary><code>Reached end of template before block expression</code></summary>

```
[HandlebarsCompilerException: Reached end of template before block expression '' was closed]
   HandlebarsDotNet.Compiler.BlockAccumulator.AccumulateBlock(IEnumerator`1 enumerator, BlockAccumulatorContext context) +411
   HandlebarsDotNet.Compiler.<ConvertTokens>d__3.MoveNext() +389
   System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) +333
   System.Linq.Enumerable.ToList(IEnumerable`1 source) +58
   HandlebarsDotNet.Compiler.BlockAccumulator.Accumulate(IEnumerable`1 tokens, HandlebarsConfiguration configuration) +97
   HandlebarsDotNet.Compiler.ExpressionBuilder.ConvertTokensToExpressions(IEnumerable`1 tokens) +268
   HandlebarsDotNet.Compiler.HandlebarsCompiler.CompileView(String templatePath) +576
   HandlebarsDotNet.HandlebarsEnvironment.CompileView(String templatePath) +101
```

</details>

---

The partial block expression works fine when the extra whitespace is removed. :tada:

```handlebars
{{#>myPartial}}
  Failover content
{{/myPartial}}
```

---

**Back story:** It's my first time using this library today - **thank you, it's great!!** I'm totally happy to contribute back a PR for this one, if you have any pointers on where to look? (I'm currently digging around the Lexer/Parser classes.)

Thanks!

**Comment by rexm** [comment]
Allowing whitespace is definitely intended. The problem is that starting [here](https://github.com/rexm/Handlebars.Net/blob/master/source/Handlebars/Compiler/Lexer/Converter/BlockAccumulators/BlockAccumulatorContext.cs#L82) and cascading down to [this entire class](https://github.com/rexm/Handlebars.Net/blob/master/source/Handlebars/Compiler/Lexer/Converter/BlockAccumulators/PartialBlockAccumulatorContext.cs) is built to assume at this point in the pipeline, a `#>name` is a single `WordToken`. Inserting the space means upstream from these components, the base parsing phase of the lexer interprets it as two separate `WordToken`s - `#>` and `name`.

The correct way to solve this, to be consistent with how other similar constructs are handled, is probably to make the parser break between `#>` and the name so they are always two words, and then in the BlockAccumulators, search for a `#>` word followed by another word that can be assumed to be the name of the partial.

PR definitely welcome!

**Comment by arsu-leo** [comment]
Would be good to at least document this behaivour on the Readme on themeantime, it took me a lot of time to find out this issue
