### ISSUE TITLE
Exception thrown for immutable array

### ISSUE THREAD

**Issue by wrong42** [Handlebars-Net/Handlebars.Net#447]
### Describe the bug
Calling `HandlebarsTemplate` fails when context contains data of type `ImmutableArray<T>`.

### Expected behavior:
Immutable arrays (structs in general) are supported as valid data types in context for template.

### Test to reproduce
```csharp
[Fact]
public void ImmutableArrayTest()
{
    var itemsList = new List<string> { "hello", "world" };
    var items = ImmutableArray.CreateRange(itemsList);

    string source =
        @"{{#each Items}}
            {{this}}
          {{/each}}";

    var template = Handlebars.Compile(source);
    var result = template(new { Items = items }); // This throws exception
}
```

### Other related info
Immutable arrays were supported in version 1.1.15. After upgrading to 2.0.7 calling the `HandlebarsTemplate` throws `System.ArgumentException` with message: "Method HandlebarsDotNet.ObjectDescriptors.EnumerableObjectDescriptor.ListObjectDescriptorFactory: type argument 'System.Collections.Immutable.ImmutableArray`1[System.Uri]' violates the constraint of type parameter 'T'."

---

### After submitting the issue
Please consider contributing to the project by submitting a PR with a fix to the issue. 
This would help to solve your problem in a shorter time as well as help other users of the project.

In case you do not know where to start - feel free to ask for help in the issue thread.

Building an active community is essential for any project survival as time of maintainers is limited.

**Comment by bsagal** [comment]
I believe this bug is related to the fact that `ImmutableArray<T>` is a `struct`.

The  `EnumerableObjectDescriptor .ListObjectDescriptorFactory<T, TValue>` [method ](https://github.com/Handlebars-Net/Handlebars.Net/blob/01ad0e69e56331371f85a1c59c008d7ecfd06f78/source/Handlebars/ObjectDescriptors/EnumerableObjectDescriptor.cs#L131)(and similar methods for other collections) has a genetic constraint of `where T : class, IList<TValue>`.

Is there a reason for the `class` constraint?

This method was added in commit 855057b.

**Comment by zjklee** [comment]
Hello @bsagal 
No, I do not think there is any real reason to have a `class` constraint.
